# Connessione al Database
spring.datasource.url=jdbc:postgresql://localhost:5432/wanted-street-food
spring.datasource.username=postgres
spring.datasource.password=Julieseal17!
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gestione Thymeleaf
spring.thymeleaf.cache=false

# Esecuzione forzata import.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true